# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 08:05
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import tg.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_class', models.SmallIntegerField(blank=True, choices=[(1, '\u666e\u901a\u80a1\u6c11'), (2, '\u6295\u987e'), (3, '\u7cfb\u7edf\u7528\u6237')], null=True, verbose_name='\u7528\u6237\u7c7b\u522b')),
                ('username', models.CharField(error_messages={'unique': '\u5df2\u5b58\u5728\u4e00\u4f4d\u4f7f\u7528\u8be5\u540d\u5b57\u7684\u7528\u6237'}, help_text='\u5fc5\u586b\u3002\u4e0d\u591a\u4e8e64\u4e2a\u5b57\u7b26\u3002\u53ea\u80fd\u7528\u5b57\u6bcd\u3001\u6570\u5b57\u548c\u5b57\u7b26 @/./+/-/_', max_length=64, unique=True, validators=[django.core.validators.RegexValidator('^[\\w.@+-]+$', '\u8bf7\u8f93\u5165\u5408\u6cd5\u7528\u6237\u540d\u3002\u53ea\u80fd\u5305\u542b\u5b57\u6bcd\uff0c\u6570\u5b57\u548c@/./+/-/_ \u5b57\u7b26')], verbose_name='\u7528\u6237\u540d')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='\u540d\u5b57')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='\u59d3\u6c0f')),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, verbose_name='\u7535\u5b50\u90ae\u4ef6\u5730\u5740')),
                ('is_staff', models.BooleanField(default=False, help_text='\u6307\u660e\u7528\u6237\u662f\u5426\u53ef\u4ee5\u767b\u5f55\u5230\u8fd9\u4e2a\u7ba1\u7406\u7ad9\u70b9', verbose_name='\u804c\u5458\u72b6\u6001')),
                ('is_active', models.BooleanField(default=True, help_text='\u6307\u660e\u7528\u6237\u662f\u5426\u88ab\u8ba4\u4e3a\u6d3b\u8dc3\u7684\u3002\u4ee5\u53cd\u9009\u4ee3\u66ff\u5220\u9664\u5e10\u53f7', verbose_name='\u6709\u6548')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u52a0\u5165\u65e5\u671f')),
                ('mobile', models.CharField(blank=True, db_index=True, max_length=16, verbose_name='\u624b\u673a\u53f7\u7801')),
                ('nick_name', models.CharField(blank=True, max_length=64, verbose_name='\u6635\u79f0')),
                ('avatar', models.ImageField(blank=True, max_length=240, null=True, upload_to=tg.models.userinfo_avatar_uploadto, verbose_name='\u5934\u50cf\u5730\u5740')),
                ('misc', models.TextField(blank=True, verbose_name='\u6742\u9879')),
            ],
            options={
                'swappable': 'AUTH_USER_MODEL',
                'db_table': 'data_user_info',
                'verbose_name': '\u7528\u6237',
                'verbose_name_plural': '\u7528\u6237',
            },
            managers=[
                ('objects', tg.models.UserInfoManager()),
            ],
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to=tg.models.ad_picture_uploadto, verbose_name='\u9898\u56fe')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='\u6807\u9898')),
                ('goto_url', models.CharField(blank=True, max_length=300, verbose_name='\u8df3\u8f6c\u7684url')),
                ('ctime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('isvalid', models.BooleanField(default=True, verbose_name='\u662f\u5426\u6709\u6548')),
            ],
            options={
                'db_table': 'data_ad',
                'verbose_name': '\u5e7f\u544a',
                'verbose_name_plural': '\u5e7f\u544a',
            },
        ),
        migrations.CreateModel(
            name='ApplyAdviserJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_name', models.CharField(max_length=40, verbose_name='\u771f\u5b9e\u59d3\u540d')),
                ('phone', models.CharField(max_length=20, verbose_name='\u624b\u673a\u53f7')),
                ('title_certificate', models.CharField(max_length=60, verbose_name='\u8d44\u8d28\u8bc1\u4e66\u53f7')),
                ('status', models.SmallIntegerField(choices=[(1, '\u5f85\u5ba1\u6838'), (2, '\u901a\u8fc7'), (3, '\u62d2\u7edd')], default=1, verbose_name='\u72b6\u6001')),
            ],
            options={
                'db_table': 'data_apply_adviser_job',
                'verbose_name': '\u7533\u8bf7\u6295\u987e\u5de5\u4f5c\u4fe1\u606f',
                'verbose_name_plural': '\u7533\u8bf7\u6295\u987e\u5de5\u4f5c\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='InvestRecommendSecurity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sec_idxid', models.CharField(help_text='\u5e02\u573a.\u80a1\u7968\u4ee3\u7801. \u5982 SZSE.000001\u4ee3\u8868\u5e73\u5b89\u94f6\u884c', max_length=20, verbose_name='\u6807\u8bc6\u80a1\u7968id')),
                ('buy_daytime', models.DateTimeField(verbose_name='\u4e70\u5165\u65f6\u95f4')),
                ('buy_price', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='\u4e70\u5165\u4ef7\u683c')),
                ('sell_daytime', models.DateTimeField(blank=True, null=True, verbose_name='\u5356\u51fa\u65f6\u95f4')),
                ('sell_price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='\u5356\u51fa\u4ef7\u683c')),
                ('ctime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('curdate_ratio', models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='\u5f53\u65e5\u6536\u76ca\u7387')),
                ('week_ratio', models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='\u5468\u6536\u76ca\u7387')),
                ('month_ratio', models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='\u6708\u6536\u76ca\u7387')),
                ('accumulate_ratio', models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='\u7d2f\u8ba1\u6536\u76ca\u7387')),
            ],
            options={
                'db_table': 'data_invest_recommend_sec',
                'verbose_name': '\u6295\u987e\u63a8\u8350\u80a1\u7968',
                'verbose_name_plural': '\u6295\u987e\u63a8\u8350\u80a1\u7968',
            },
        ),
        migrations.CreateModel(
            name='InvestViewpoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='\u6807\u9898')),
                ('digest', models.CharField(blank=True, max_length=400, verbose_name='\u6458\u8981')),
                ('content', models.CharField(blank=True, max_length=20480, verbose_name='\u5185\u5bb9')),
                ('pub_daytime', models.DateTimeField(blank=True, null=True, verbose_name='\u53d1\u5e03\u65f6\u95f4')),
                ('sub_picture', models.ImageField(blank=True, max_length=320, null=True, upload_to=tg.models.investviewpoint_subpic_uploadto, verbose_name='\u914d\u56fe')),
            ],
            options={
                'db_table': 'data_invest_viewpoint',
                'verbose_name': '\u6295\u8d44\u89c2\u70b9',
                'verbose_name_plural': '\u6295\u8d44\u89c2\u70b9',
            },
        ),
        migrations.CreateModel(
            name='PortfolioBaseInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=100, unique=True, verbose_name='\u6765\u81ea\u4e8eapi\u521b\u5efa\u7684\u6295\u7ec4id')),
                ('name', models.CharField(max_length=100, verbose_name='\u540d\u79f0')),
                ('topics', models.CharField(blank=True, max_length=100, verbose_name='\u4e3b\u9898')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='\u8bf4\u660e')),
                ('ctime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('curdate_ratio', models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='\u5f53\u65e5\u6536\u76ca\u7387')),
                ('week_ratio', models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='\u5468\u6536\u76ca\u7387')),
                ('month_ratio', models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='\u6708\u6536\u76ca\u7387')),
                ('accumulate_ratio', models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='\u7d2f\u8ba1\u6536\u76ca\u7387')),
            ],
            options={
                'db_table': 'data_portfolio_baseinfo',
                'verbose_name': '\u6295\u8d44\u7ec4\u5408\u57fa\u672c\u4fe1\u606f',
                'verbose_name_plural': '\u6295\u8d44\u7ec4\u5408\u57fa\u672c\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='SecModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sec_type', models.IntegerField(verbose_name='\u7c7b\u578b')),
                ('sec_id', models.CharField(db_index=True, max_length=12, verbose_name='\u4ee3\u7801')),
                ('sec_name', models.CharField(max_length=32, verbose_name='\u540d\u79f0')),
                ('exchange', models.CharField(max_length=8, verbose_name='\u5e02\u573a\u4ee3\u7801')),
                ('is_active', models.BooleanField(default=True, verbose_name='\u662f\u5426\u6709\u6548')),
            ],
            options={
                'db_table': 'data_sec_model',
                'verbose_name': '\u8bc1\u5238\u4fe1\u606f',
                'verbose_name_plural': '\u8bc1\u5238\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='SignContract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='\u5907\u6ce8\u8bf4\u660e')),
            ],
            options={
                'db_table': 'data_sign_contract',
                'verbose_name': '\u7528\u6237\u7b7e\u7ea6\u6295\u987e',
                'verbose_name_plural': '\u7528\u6237\u7b7e\u7ea6\u6295\u987e',
            },
        ),
        migrations.CreateModel(
            name='SnsFollow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'data_sns_follow',
                'verbose_name': '\u7528\u6237\u95f4\u5173\u6ce8',
                'verbose_name_plural': '\u7528\u6237\u95f4\u5173\u6ce8',
            },
        ),
        migrations.CreateModel(
            name='SubscribePortfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='\u5907\u6ce8\u8bf4\u660e')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tg.PortfolioBaseInfo', verbose_name='\u6295\u7ec4')),
            ],
            options={
                'db_table': 'data_subscribe_portfolio',
                'verbose_name': '\u7528\u6237\u8ba2\u9605\u7ec4\u5408',
                'verbose_name_plural': '\u7528\u6237\u8ba2\u9605\u7ec4\u5408',
            },
        ),
        migrations.CreateModel(
            name='InvestAdviserInfo',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('title', models.CharField(blank=True, max_length=60, null=True, verbose_name='\u804c\u79f0')),
                ('title_certificate', models.CharField(blank=True, max_length=60, verbose_name='\u8d44\u8d28\u8bc1\u4e66\u53f7')),
                ('experience', models.CharField(blank=True, max_length=2048, verbose_name='\u4ece\u4e1a\u7ecf\u9a8c')),
                ('good_at', models.CharField(blank=True, max_length=2048, verbose_name='\u64c5\u957f\u9886\u57df')),
            ],
            options={
                'db_table': 'data_invest_adv_info',
                'verbose_name': '\u6295\u987e\u4fe1\u606f',
                'verbose_name_plural': '\u6295\u987e\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='InvestAdviserKpi',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('success_ratio', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='\u8350\u80a1\u6210\u529f\u7387')),
                ('accumulate_profit_ratio', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='\u7d2f\u8ba1\u6536\u76ca\u7387')),
            ],
            options={
                'db_table': 'data_invest_adv_kpi',
                'verbose_name': '\u6295\u987ekpi\u6307\u6807\u503c',
                'verbose_name_plural': '\u6295\u987ekpi\u6307\u6807\u503c',
            },
        ),
        migrations.CreateModel(
            name='UserStatistic',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('fans_count', models.PositiveIntegerField(default=0, verbose_name='\u7c89\u4e1d\u6570')),
                ('followings_count', models.PositiveIntegerField(default=0, verbose_name='\u5173\u6ce8\u6570')),
                ('sign_contract_count', models.PositiveIntegerField(default=0, verbose_name='\u7b7e\u7ea6\u80a1\u6c11\u6570')),
                ('recommend_secs_count', models.PositiveIntegerField(default=0, verbose_name='\u63a8\u8350\u80a1\u7968\u6570')),
                ('portfolios_count', models.PositiveIntegerField(default=0, verbose_name='\u6295\u8d44\u7ec4\u5408\u6570')),
                ('portfolios_bysubscribe_count', models.PositiveIntegerField(default=0, verbose_name='\u6295\u8d44\u7ec4\u5408\u88ab\u8ba2\u9605\u6b21\u6570')),
                ('viewpoints_count', models.PositiveIntegerField(default=0, verbose_name='\u6295\u8d44\u89c2\u70b9\u6570')),
            ],
            options={
                'db_table': 'data_user_stat',
                'verbose_name': '\u7528\u6237\u7edf\u8ba1\u4fe1\u606f',
                'verbose_name_plural': '\u7528\u6237\u7edf\u8ba1\u4fe1\u606f',
            },
        ),
        migrations.AddField(
            model_name='subscribeportfolio',
            name='user',
            field=models.ForeignKey(db_column='uid', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='\u8ba2\u9605\u8005'),
        ),
        migrations.AddField(
            model_name='snsfollow',
            name='followee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='snsfollow',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='signcontract',
            name='adviser',
            field=models.ForeignKey(db_column='adviser_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='\u6295\u987e'),
        ),
        migrations.AddField(
            model_name='signcontract',
            name='user',
            field=models.ForeignKey(db_column='uid', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237'),
        ),
        migrations.AddField(
            model_name='portfoliobaseinfo',
            name='owner',
            field=models.ForeignKey(db_column='own_uid', on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='investviewpoint',
            name='owner',
            field=models.ForeignKey(db_column='own_uid', on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='investrecommendsecurity',
            name='owner',
            field=models.ForeignKey(db_column='own_uid', on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AlterUniqueTogether(
            name='subscribeportfolio',
            unique_together=set([('user', 'portfolio')]),
        ),
        migrations.AlterUniqueTogether(
            name='snsfollow',
            unique_together=set([('user', 'followee')]),
        ),
    ]
