# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='secmodel',
            name='symbol',
            field=models.CharField(db_index=True, default='', max_length=40, verbose_name='\u8bc1\u5238\u6807\u8bc6(\u5e02\u573a.\u4ee3\u7801)'),
            preserve_default=False,
        ),
    ]
