# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 04:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0002_add_symbol2secmode'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='gender',
            field=models.SmallIntegerField(choices=[(1, '\u7537'), (2, '\u5973'), (3, '\u4fdd\u5bc6')], default=3, verbose_name='\u6027\u522b'),
        ),
    ]
