# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0003_add_gender2userinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliobaseinfo',
            name='success_ratio',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='\u8350\u80a1\u6210\u529f\u7387'),
        ),
    ]
