# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 02:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0005_add_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investrecommendsecurity',
            name='owner',
            field=models.ForeignKey(db_column='own_uid', on_delete=django.db.models.deletion.CASCADE, related_name='recommend_securitys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='investviewpoint',
            name='owner',
            field=models.ForeignKey(db_column='own_uid', on_delete=django.db.models.deletion.CASCADE, related_name='viewpoints', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='portfoliobaseinfo',
            name='owner',
            field=models.ForeignKey(db_column='own_uid', on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_base_infos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='signcontract',
            name='adviser',
            field=models.ForeignKey(db_column='adviser_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='sign_investors', to=settings.AUTH_USER_MODEL, verbose_name='\u6295\u987e'),
        ),
        migrations.AlterField(
            model_name='signcontract',
            name='user',
            field=models.ForeignKey(db_column='uid', on_delete=django.db.models.deletion.DO_NOTHING, related_name='sign_advisers', to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237'),
        ),
        migrations.AlterField(
            model_name='snsfollow',
            name='followee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='snsfollow',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subscribeportfolio',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='subscribe_investors', to='tg.PortfolioBaseInfo', verbose_name='\u6295\u7ec4'),
        ),
        migrations.AlterField(
            model_name='subscribeportfolio',
            name='user',
            field=models.ForeignKey(db_column='uid', on_delete=django.db.models.deletion.DO_NOTHING, related_name='subscribe_portfolios', to=settings.AUTH_USER_MODEL, verbose_name='\u8ba2\u9605\u8005'),
        ),
    ]
